### ISSUE TITLE
Running on large jp2 WSI files

### ISSUE THREAD

**Issue by supritimulay** [Lee-Gihun/MEDIAR#1]
Thank you for uploading this wonderful segmentation code. Can this be run on large tif or jp2 WSI images? How can we run this for large WSI files?

**Comment by Lee-Gihun** [comment]
Yes, we tested on WSIs (with `.tif` or `.tiff` extention) in the inference time, and it works well.

However, due to the memory & time efficiency, MEDIAR conducts the inference greedily using the `2000*2000` RoI size. If you have enough computational resources, you can comment out the related part below:
https://github.com/Lee-Gihun/MEDIAR/blob/916434faebdc155e07f0db81af1a51cb899cfad5/core/MEDIAR/Predictor.py#L103-L156

FYI, it didn't work well when I tested the currently trained model on H&E-stained WSIs. It could be due to those images not being in the trained datasets, which indicates you need to fine-tune the model with few labeled images in such cases.

**Comment by supritimulay** [comment]
Thank you, I am having enough computational resource, and tried to segment ~4GB *.tiff file with the above code commenting but program is getting killed and no error is shown. Can you please help me on how I can proceed further?

**Comment by Lee-Gihun** [comment]
I guess it might be the internal python, which usually due to the bad memory allocation. You can check the followings:

- Does it work when using 2000x2000 RoI size, with a greedy manner (the code in the else statement")?
- Does it work when using CPU?
  - set `use_gpu=False` at the following code (It takes really long..., maybe more than 1hr):
  - https://github.com/Lee-Gihun/MEDIAR/blob/916434faebdc155e07f0db81af1a51cb899cfad5/core/MEDIAR/Predictor.py#L97
- Does it stuck by the insufficient (cpu) memory?
  - Cut the Image smaller (maybe ~ 1GB?) and conduct inference again. 
- Is the issue only related to the "gradient tracking"? Does it work until the beginning of the post-processing?
  - To check it, just add `print(dP)` and `print(cellprob)` under the line below:
  - https://github.com/Lee-Gihun/MEDIAR/blob/916434faebdc155e07f0db81af1a51cb899cfad5/core/MEDIAR/Predictor.py#L90
  - If it stuck in here, actually we do not know much of how to figure it out, as our post-processing code is just a 2D refactored version of the original [CellPose gradient tracking](https://github.com/MouseLand/cellpose/blob/main/cellpose/dynamics.py).

**Comment by supritimulay** [comment]
Thank you. For smaller tiles algorithm is working absolutely fine. I am trying to make tile and run this algo but it requires all argument with input path and other more. Are you having any version of this program for WSI which will create tile  run MEDIAR and again stitch it back.  Thank you.

**Comment by Lee-Gihun** [comment]
We currently do not support such function yet. However, I think that tiled inference and stitching back is an interesting and very useful extension. Let us include the function at the next version. We're planning to improve some usability of MEDIAR, maybe late this month.

**Comment by supritimulay** [comment]
Thank you!
