### ISSUE TITLE
current Mediar weights

### ISSUE THREAD

**Issue by marius10p** [Lee-Gihun/MEDIAR#19]
This is a small thing, but I was wondering how the current Mediar weights differ from the ones submitted to the challenge, if at all. We ran Mediar on the tuning set of the challenge using the [evaluation code](https://github.com/JunMa11/NeurIPS-CellSeg/blob/main/baseline/compute_metric.py), and obtained a median F1 score of 0.9126 with TTA and ensembling ([this json](https://github.com/Lee-Gihun/MEDIAR/blob/main/config/step3_prediction/ensemble_tta.json)). Without TTA and ensembling, the median F1 score was 0.9091 ([this json](https://github.com/Lee-Gihun/MEDIAR/blob/main/config/step3_prediction/base_prediction.json)). 

In the [Mediar paper](https://arxiv.org/abs/2212.03465) you report 0.9067, which nearly matches the largest score on the [leaderboard](https://neurips22-cellseg.grand-challenge.org/evaluation/challenge/leaderboard/) of 0.9070. 

Thanks.

**Comment by Lee-Gihun** [comment]
Oh, we hadn't even noticed that! Regarding your question, the current MEDIAR weights are exactly the same as the ones submitted to the challenge.

However, for the version of the prediction submitted, we limited the overlap size between patches and excluded TTA and ensembling for some images due to the time efficiency metric of the challenge evaluation. This was to ensure the running time met the time constraints. I think this might be the reason the score differs.

**Comment by marius10p** [comment]
I see, that makes sense, thanks so much for explaining.
